### ISSUE TITLE
Modify the Trace original code

### ISSUE THREAD

**Issue by asmirn1** [du-lab/Trace#2]
@jerrychen04 @du-lab I think, we need to make the following changes to the existing Trace code:
- Put all the parameters into a separate class (Let's call it `Config` for example). This will help us to modify these parameters from GUI. It might also be useful to have three config classes `PeakPickingConfig`, `ImageConfig`, `ClassifierConfig`.
- Put the file importing code into a separate class, e.g. `MzXMLReader`. Because we might want to display the raw data first and then let users choose parameters. In this case, we'll need to read the raw data file before we execute the rest of the  workflow.
- Create a new class `TraceResults` that stores all the results from executing the workflow, including all the peaks detected by CWT, the corresponding images, and the neural-network predictions. This will help us to display the results in GUI.

Let me know what do you think.

**Comment by jerrychen04** [comment]
There is already a separate class called `mzmlReadRaw` , which reads raw data. Therefore, we can use the functions in this script specifically to read the raw data before executing the rest of the workflow. For the results display on the GUI, we can use the directory created by Trace called `Results` which has all the results from the workflow stored inside it and we can simply reference the path to the files inside and display them. 

Organizing all the variables into one file may be beneficial for ease of coding with the GUI but when executing a Flask application we can set variables equal to a request from the web app instead of the hard-coded values, for example:

Instead of:
` ################### Important Paramenters To Be Changed ###################`
`mz_min = 25.000        # The minimum of m/z to be evaluated`
`mz_max = 550.01        # The maximum of m/z to be evaluated`
`mz_r  = 0.0050         # The m/z bin for signal detection and evaluation (window is +/- this value)`

We can use: 

`from flask import Flask, request`
`################### Important Paramenters To Be Changed ###################`
`mz_min = request.args.get('mz_min', '')        # The minimum of m/z to be evaluated`
`mz_max = request.args.get('mz_max', '')        # The maximum of m/z to be evaluated`
`mz_r  = request.args.get('mz_r', '')         # The m/z bin for signal detection and evaluation (window is +/- this value)`

**Comment by du-lab** [comment]
The parameters that users supply through the GUI still need to be stored in a parameter class where all the parameters are stored.

**Comment by asmirn1** [comment]
@jerrychen04 I agree with @du-lab It'll be better to keep all the parameters in one dedicated class. We'll use GUI to modify this class, and Trace code should read parameters from that class.

As a side note: we still want to keep an ability to run Trace from a command-line without GUI. So the Trace code should be separated from the Flask code.

Regarding results: reading from and writing to a disk is much slower than working with a memory. So I writing the Trace results on disk and then reading them to display in GUI will be slow and prone to errors. I think that the better approach is to create a class `TraceResults` that we can directly use in GUI.

**Comment by jerrychen04** [comment]
> @jerrychen04 I agree with @du-lab It'll be better to keep all the parameters in one dedicated class. We'll use GUI to modify this class, and Trace code should read parameters from that class.
> 
> As a side note: we still want to keep an ability to run Trace from a command-line without GUI. So the Trace code should be separated from the Flask code.
> 
> Regarding results: reading from and writing to a disk is much slower than working with a memory. So I writing the Trace results on disk and then reading them to display in GUI will be slow and prone to errors. I think that the better approach is to create a class `TraceResults` that we can directly use in GUI.

Do we want just one function like `def setVarAll(window_mz, BIG_RAM, etc):` inside the `MasterConfig` script and set all the parameters inside that python script? So when other scripts use the variables, they will just import the specific parameters from the master class like `from MasterConfig import mz_min, mz_max, etc`

**Comment by asmirn1** [comment]
@jerrychen04 

I don't think you need function `setVarAll()`. I guess, you would have to pass a few dozen parameters to that function, which isn't good. Instead, you can specify default values for each parameter in `MasterConfig`. Then users will be able to modify some of the parameters later.

Using `from MasterConfig import mz_min, mz_max, etc` isn't good approach. Because `MasterConfig` will be imported only once when the script is first executed, so we won't be able to change those parameters programmatically. Instead, I'm thinking more like this:
```python
params = MasterConfig()  # params will contain all parameters with their default values
params.window_mz = 10  # we should be able to change some values in the code if needed

# Then we'll pass `params` to each step of Trace. Each step should use the parameters from `params`
pks_initial = scan_mp(params, r"C:\Users\jerry\Desktop\IC1_22.mzML", RESULTS_PATH = RESULTS_PATH, NUM_C = NUM_C )  ##

images = get_image(params, r"C:\Users\jerry\Desktop\IC1_22.mzML", pks_initial, RESULTS_PATH, Big_RAM, window_mz, window_rt)

pks_final = predict(params, images, pks_initial, RESULTS_PATH = RESULTS_PATH, K_means = K_MEANS )

```

**Comment by asmirn1** [comment]
TODO:
- Create class `Peak` and use list of Peaks in each step
- Create an export function to save peaks to CSV file
- Log parameters of every step

**Comment by jerrychen04** [comment]
Finished TODO. Can you review the code in my latest commit and its changes? Code may not be fully functional with K_means and Plot_Images parameters enabled but they are not essential to the workflow. Also, we may need to adjust the image module if we want BIG_RAM to work with the new peak array.
